### ISSUE TITLE
`$ vs. MWE

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#43]
New Year 'S resolution

We went with `$ but aren't sure if that's a proper use of the tag. Gestalt and Circumstance were also considered.

**Comment by nschneid** [comment]
Or Time?

**Comment by nschneid** [comment]
Another option would be New_Year_'s as an MWE. I think with the possessive it refers to the observance specifically (presumably from shortening New Year's Eve / Day), as opposed to the new year itself. E.g. on Jan. 1 one could receive a New Year's gift, but not a *New Year gift. And it can stand alone: "Is it New Year's yet?"

This reminds me of the locative genitive ("I went to Kroger's"). In STREUSLE the locative genitive instances are treated as MWEs, though I'm not sure `$ wouldn't be preferable because the pattern is productive. By contrast, most holidays do not take the possessive (*Is it Thanksgiving's yet?). So treating "New Year's" as an MWE does seem justified.

**Comment by esmanning** [comment]
Somewhat related: 

Master 'S Thesis

Similar to New Year's, there's an implicit governor of the possessive (Master's degree), and it can stand alone ("I'm getting a master's")

Works for some other degree type (e.g. Bachelor's) but I don't think it's productive beyond a small set.

MWE? or `$?

**Comment by nschneid** [comment]
I like MWE for "master's" and "bachelor's", especially since the normal meaning of the noun isn't applicable anyway.

**Comment by nschneid** [comment]
https://twitter.com/LaymansLinguist/status/1212395116188569602

**Comment by nschneid** [comment]
New_Year_'s resolution = resolution for New_Year_'s. Possessive goes with the entity, not relating "New Year" to "resolution"

master_'s thesis = thesis for a master_'s (*master)
