### ISSUE TITLE
writing a thesis FOR an institution

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#46]
Possibly Beneficiary (or Purpose if an institution isn't animate enough): the university probably does benefit from students' research, but unsure if that's the best reading

Also discussed for comparison:
I'm writing a report FOR chemistry class

In which case, unlike the university, the class is clearly not benefiting from the report. I think we agree this would be Explanation, but are unsure if it fits the thesis example.

**Comment by nschneid** [comment]
The report for the class seems like Purpose to me. We understand it to mean "in order to complete the requirements of the class".

I'm not sure I would say someone is writing a thesis FOR Georgetown. Is the reading that the institution demands a thesis in exchange for a degree? Or is Georgetown standing for the studies/degree being pursued at Georgetown?

**Comment by nschneid** [comment]
Purpose
