### ISSUE TITLE
several counts OF murder

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#75]
> He assisted in several counts OF murder and attempted murder
task_005
new_doc id = b7b4ea19-f3c6-0ca9-f523-ae25f9908c04
sent_id = 4

This was left blank in the original adjudication in summer! We just found it while working on updating the data, and I don't see a previous issue for it.

There was debate over the semantics of "counts" here - could be QuantityItem or QuantityItem~Gestalt, or could be Topic?

**Comment by nschneid** [comment]
Plain QuantityItem is used for "a piece OF cake", where "piece" is a unitizer (classifier) that discretizes cake. Is the legal sense of "count" working similarly, to turn the crime (murder) into a countable number of legal violations? ("How much murder was he accused of? Several counts.") Maybe, but it feels like a stretch because you can talk about "murders" as well.

QuantityItem~>Gestalt would apply if we are considering "count" as like "number", but you can't paraphrase "He assisted in several numbers of murder" or "a large number of murders". "Count" is actually providing a legal perspective on the event.

I think Topic makes sense as the scene role. One possibility is that "counts" is a shell noun, a vague conceptual word like "issue" in "the issue OF semantics", which is Topic~>Identity in the guidelines. But "counts of murder" is a bit different from "murder(s)" because it is explicitly about legal charges, which are/involve acts of communication. So plain Topic seems fine to me.

**Comment by nschneid** [comment]
@dhwang90 agrees. **plain Topic**
